# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
