# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Investor',
            new_name='investor',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Startup',
            new_name='startup',
        ),
    ]
