# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_auto_20170828_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='startups',
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Startup name'),
        ),
    ]
