# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_auto_20170828_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='passport',
            field=models.ImageField(upload_to='static/images/passport'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/logo'),
        ),
    ]
